name: vocus-converter
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python = 3.11
  - pip
  - beautifulsoup4
  - requests
  - html2text
  - weasyprint
  - pip:
    - lxml
    - Pillow
    - pywebview